name: '[Main] lint, build_export and deploy'

on: push

# secrets:
#   GCP_PROJECT_ID: id of the GCP project
#   GCP_SA_KEY: json of service account's to access the GCP bucket
#   GCP_BUCKET_NAME: GCP bucket name (object storage)

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: cp src/env.js.dev src/env.js
    - run: npm run ci-tc

  build_export:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: cp src/env.js.prod src/env.js
    - run: npm run build
    - name: upload exported build
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build_export
    runs-on: ubuntu-latest

    steps:
    - name: download exported build
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gsutil -m -h "Cache-Control:no-cache, max-age=0" rsync -r -d dist/ "gs://${GCP_BUCKET_NAME}/"
      env:
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
